// <auto-generated />
using EnitityFrameworkCodeFirstApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnitityFrameworkCodeFirstApp.Migrations
{
    [DbContext(typeof(DBcontextFile))]
    [Migration("20250606093844_addProduvt")]
    partial class addProduvt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnitityFrameworkCodeFirstApp.Models.Product", b =>
                {
                    b.Property<int>("Product_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_no"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Product_Color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Product_Name");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Product_size");

                    b.HasKey("Product_no");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("EnitityFrameworkCodeFirstApp.Models.Students", b =>
                {
                    b.Property<int>("RollNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RollNO"));

                    b.Property<int>("Dob")
                        .HasColumnType("int");

                    b.Property<int>("MobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("StdName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollNO");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EnitityFrameworkCodeFirstApp.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MobileNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
